force-app/main/default/objects/Individual_ID__c/Individual_ID__c.object-meta.xml
<CustomObject>
    <description>Table for keeping track of Individuals with their Id Numbers.</description>
    <label>Individual ID</label>
    <nameField>
        <label>Individual ID Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Individual IDs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Individual_ID__c/fields/Citizenship__c.field-meta.xml
<CustomField>
    <fullName>Citizenship__c</fullName>
    <label>Citizenship</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Citizen</fullName>
            </value>
            <value>
                <fullName>Permanent Resident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Individual_ID__c/fields/Id_Number__c.field-meta.xml
<CustomField>
    <fullName>Id_Number__c</fullName>
    <externalId>true</externalId>
    <label>Id Number</label>
    <length>13</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
public class TestDataFactory {

    // Static method to create an Individual_ID__c record
    public static Individual_ID__c createIndividualId(String citizenship, String gender, Date dateOfBirth, String name, String indIDNumber) {
        Individual_ID__c newIndId = new Individual_ID__c();
        newIndId.Citizenship__c = citizenship;
        newIndId.Gender__c = gender;
        newIndId.Date_Of_Birth__c = dateOfBirth;
        newIndId.Name = name;
        newIndId.Id_Number__c = indIDNumber;

        // Insert the new Individual_ID__c record
        insert newIndId;

        return newIndId;
    }
}